### ISSUE TITLE
Skid

### ISSUE THREAD

**Issue by YABOIpy** [Kolonyaa/sauce#1]
Cunny
![monkey-artificialbloom.gif](https://user-images.githubusercontent.com/110062350/184040359-04c58ae7-d984-490e-86f5-c4157a569186.gif)

**Comment by Kolonyaa** [comment]
kys

**Comment by YABOIpy** [comment]
Pooron

**Comment by Kolonyaa** [comment]
nah u the one who can't afford crypto 🤣🤣☝️☝️

**Comment by YABOIpy** [comment]
U the one who can't buy it https://user-images.githubusercontent.com/110062350/184045173-3ecc3421-c245-4dc3-afe6-eb8897ddc850.mp4

**Comment by Kolonyaa** [comment]
I can't believe that's a death threat..... 😭😭
